### ISSUE TITLE
Add Build Types

### ISSUE THREAD

**Issue by sami-eljabali** [seljabali/todo-list-spring-boot-webflux-kotlin#8]
Add 3 build types:
- Production
- Staging
- Development

Each build type allows configuration of:
- Database
	- URL
	- Name
	- Password
- Allowed origin URL
- Base URL of project

**Comment by hantsy** [comment]
Spring Boot support multi profiles to be active in different environments, but this can be active at runtime, it satisfies the 12factor app requirements.

Currently in this project, I added some profile aware application config and some different config in these profiles.

1. Database related settings are Spring Built-in properties, change them as you expected in other profiles(such as prod, staging). **But they are sensitive info, so it is better to create env variables or configMap(k8s) like vars to override the default values**.
2. `Allowed origin URL` and `Base URL of project` can be configured under *app* prefix, defined in `AppProperties`.
3. I assume the Allowed origin URL is used to setup cors, I added cors config for it. In fact, in the past years, I would like use an inverse proxy in the frontend instead of using it.
